### ISSUE TITLE
gradle wrapper bugs

### ISSUE THREAD

**Issue by dreamlibrarian** [daedalus4096/PrimalMagic#11]
Two bits of fun:

* gradlew (the *nix wrapper script) isn't executable on linux, minor wart: `git update-index --chmod=+x gradlew` would remediate that. 

* Running gradlew nets me an error:

```Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain```

This seems to be because the gradle/ tree appears to have .gitignored the jarfiles that belong in it in order to have a viable gradle build.

Most likely this could be remediated by adding a line `!gradle` to your .gitignore and `git add gradle` to get the jarfile included. 

If you want to see what's up, `git check-ignore --verbose gradle/wrapper/gradle-wrapper.jar` should tell you which pattern in .gitignore is blocking the file. 

I'm trying to rebuild the wrapper from scratch and am probably just tripping on dumb stuff.

**Comment by dreamlibrarian** [comment]
Arright: successfully got my local env sorted by running `mdk/gradlew wrapper` from the project tree, so looks like this is relatively easy to recover from.

**Comment by daedalus4096** [comment]
Thanks for the PR!
